"""GENERATED by tag_flying.py — do not edit by hand.

Unconditional flying for every creature in the three decks,
read from Scryfall's `keywords` array. Conditional fliers are
NOT here: see opponents.flying_of(). Regenerate with
`python tag_flying.py --write` after any deck change.
"""

FLYING = {
    'Archangel of Thune',
    'Cliffhaven Vampire',
    "Drana's Emissary",
    'Exemplar of Light',
    'Junk Diver',
    'Lorehold, the Historian',
    'Ornithopter of Paradise',
    'Starscape Cleric',
    'Sunscorch Regent',
}

# Token subtypes that fly, from the text of the card that makes them.
FLYING_TOKENS = {
    'Angel',
    'Bird',
    'Faerie',
    'Pegasus',
}
