"""GENERATED by tag_flying.py — do not edit by hand.

Unconditional flying for every creature in the three decks,
read from Scryfall's `keywords` array. Conditional fliers are
NOT here: see opponents.flying_of(). Regenerate with
`python tag_flying.py --write` after any deck change.
"""

FLYING = {
    'Archangel of Thune',
    'Caldera Pyremaw',
    'Cliffhaven Vampire',
    'Custodi Squire',
    'Cyberdrive Awakener',
    "Drana's Emissary",
    'Exemplar of Light',
    'Goldspan Dragon',
    'Junk Diver',
    'Lorehold, the Historian',
    'Magister of Worth',
    'Messenger Jays',
    'Mirkwood Bats',
    'Ornithopter of Paradise',
    'Starscape Cleric',
    'Sunscorch Regent',
    'Tivit, Seller of Secrets',
}

# Token subtypes that fly, from the text of the card that makes them.
FLYING_TOKENS = {
    'Angel',
    'Bird',
    'Faerie',
    'Pegasus',
}
