"""
Trostani, Selesnya's Voice v1 — deck definition.

    Trostani, Selesnya's Voice  {G}{G}{W}{W}  2/5
      Whenever another creature you control enters, you gain life equal to
      that creature's toughness.
      {1}{G}{W}, {T}: Populate. (Create a token that's a copy of a creature
      token you control.)

THE LIST is the owner's spreadsheet of 2026-10-01
(`spreadsheets/Trostani_Selesnyas_Voice_Commander_Deck_v1.xlsx`), 99 cards and
the commander. Three names in it were misspelt and are corrected here, each
resolved by Scryfall's fuzzy match and then checked by eye against the card:

    "Angle of Sanctions"    -> Angel of Sanctions
    "Sylvain Caryatid"      -> Sylvan Caryatid
    "Luminarch Ascention"   -> Luminarch Ascension

and "Beast Within " carried a trailing space. Costs, P/T, card types and
keywords are hand-authored against Scryfall oracle text, verified
2026-10-01; FLYING / INDESTRUCTIBLE / the subtype and LEGENDARY sets come from
`decks/_evasion.py`, generated by `python -m tools.tag_flying --write`, never
typed here.

THE DECK'S THESIS, the owner's words: "create and duplicate tokens; large
token makers such as Soul of Eternity are some of the MVPs". The engine that
makes that true is in `edhmc/trostani.py`'s docstring -- Trostani's lifegain
reads the TOUGHNESS of what enters, and Soul of Eternity's toughness IS your
life total, so every token copy of Soul doubles your life.

PRIORITIES AND THREATS ARE A FIRST GUESS, as they were for shilgengar and
azusa on their first day. Priority is the greedy casting order (queued item
18: the weakest link), threat is how badly the pod wants a permanent dead;
neither is a measurement.

TAGS THE ENGINE READS (a tag nothing reads is a loaded gun, §0z12 -- every one
below has a reader in `edhmc/trostani.py`, by the same name):

    land entry   "shock"  (pay 2 life or enter tapped), "check" (untapped if
                 you control a Forest or a Plains), "battle" (untapped with
                 two or more basic lands), "reveal" (untapped if you reveal a
                 Forest or Plains card from hand), "gain1", "scry1",
                 "hideaway4", "cycling2", "bounce" (also read by the shared
                 `available_mana`: a Karoo taps for two)
    fetchlands   "fetch" plus "fetch_Forest" / "fetch_Plains": what the
                 land's text lets it search for, out of {Forest, Plains}.
                 Verdant Catacombs' Swamp, Flooded Strand's Island and the
                 rest are the halves this list cannot find and are not tagged.
"""

from edhmc.engine import Card
from edhmc.decks._evasion import FLYING, INDESTRUCTIBLE


def C(name, types, cost=None, p=0, t=0, script=None, priority=0.0, tags=(),
      threat=0.0, mana=None, lifelink=False, tapped=False, x_pips=0,
      alt_costs=()):
    ma = (mana[0], frozenset(mana[1])) if mana else None
    return Card(name=name, types=frozenset(types.split("/")), cost=cost or {},
                power=p, toughness=t, script=script, priority=priority,
                threat=threat, tags=frozenset(tags), mana_ability=ma,
                lifelink=lifelink, tapped=tapped, x_pips=x_pips,
                alt_costs=alt_costs,
                flying=name in FLYING,
                indestructible=name in INDESTRUCTIBLE)


def L(name, produces, tapped=False, types="Land", tags=()):
    return Card(name=name, types=frozenset(types.split("/")), is_land=True,
                produces=frozenset(produces), tapped=tapped,
                tags=frozenset(tags),
                indestructible=name in INDESTRUCTIBLE)


COMMANDER = C("Trostani, Selesnya's Voice", "Creature",
              {"G": 2, "W": 2}, 2, 5, priority=10, threat=8.0)

# ---------------------------------------------------------------------------
# Token makers, populate and copy effects -- the deck's engine
# ---------------------------------------------------------------------------
TOKENS = [
    # "Soul of Eternity's power and toughness are each equal to your life
    # total." p/t 0 here; `TrostaniGame.power_of` computes it.
    C("Soul of Eternity", "Creature", {"gen": 5, "W": 2}, 0, 0,
      priority=9, threat=9.0),
    C("Bramble Sovereign", "Creature", {"gen": 2, "G": 2}, 4, 4,
      priority=10.5, threat=8.0),  # §0z110: priority 8.5 -> 10.5, adopted 2026-10-05
    C("Seedborn Muse", "Creature", {"gen": 3, "G": 2}, 2, 4,
      priority=10, threat=7.5),  # §0z110: priority 8 -> 10, adopted 2026-10-05
    C("Elspeth, Sun's Champion", "Planeswalker", {"gen": 4, "W": 2},
      priority=8.5, threat=8.5),
    # {2}{G/W}{G/W}: the printed cost is one spelling; the hybrid alts are the
    # other two (the Lurrus convention, `engine.hybrid_pips`).
    C("Growing Ranks", "Enchantment", {"gen": 2, "G": 2}, priority=7.5,
      threat=6.5, alt_costs=(({"gen": 2, "W": 2}, "hybrid"),
                             ({"gen": 2, "G": 1, "W": 1}, "hybrid"))),
    C("Nesting Dovehawk", "Creature", {"gen": 3, "W": 1}, 2, 2,
      priority=9, threat=6.0),  # §0z110: priority 7 -> 9, adopted 2026-10-05
    C("Selesnya Eulogist", "Creature", {"gen": 2, "G": 1}, 3, 3,
      priority=6.5, threat=5.0),
    C("Luminarch Ascension", "Enchantment", {"gen": 1, "W": 1},
      priority=7, threat=6.0),
    C("Dawn of Hope", "Enchantment", {"gen": 1, "W": 1}, priority=6.5,
      threat=5.0),
    C("Caretaker's Talent", "Enchantment", {"gen": 2, "W": 1},
      priority=7.5, threat=6.5),
    C("Phyrexian Processor", "Artifact", {"gen": 4}, priority=6.5,
      threat=7.0),
    C("Mimic Vat", "Artifact", {"gen": 3}, priority=6, threat=5.5),
    C("God-Pharaoh's Gift", "Artifact", {"gen": 7}, priority=6.5,
      threat=7.5),
    C("Blade of Selves", "Artifact", {"gen": 2}, priority=6, threat=5.0),
    C("King Darien XLVIII", "Creature", {"gen": 1, "G": 1, "W": 1}, 2, 3,
      priority=9, threat=6.5),  # §0z110: priority 7 -> 9, adopted 2026-10-05
    # "Queen Allenal of Ruadach's power and toughness are each equal to the
    # number of creatures you control."
    C("Queen Allenal of Ruadach", "Creature", {"G": 1, "W": 2}, 0, 0,
      priority=7.5, threat=7.0),
    C("Wurmcoil Engine", "Artifact/Creature", {"gen": 6}, 6, 6,
      priority=7, threat=8.0, lifelink=True),
    # {G/W}{G/W}: destroy target artifact or enchantment, then populate.
    C("Sundering Growth", "Instant", {"G": 2}, priority=4,
      alt_costs=(({"W": 2}, "hybrid"), ({"G": 1, "W": 1}, "hybrid"))),
]

# ---------------------------------------------------------------------------
# Token doublers (replacement effects on the ONE token path)
# ---------------------------------------------------------------------------
DOUBLERS = [
    C("Anointed Procession", "Enchantment", {"gen": 3, "W": 1},
      priority=8, threat=7.5),
    C("Parallel Lives", "Enchantment", {"gen": 3, "G": 1},
      priority=8, threat=7.5),
    C("Mondrak, Glory Dominus", "Creature", {"gen": 2, "W": 2}, 4, 4,
      priority=8.5, threat=8.0),
    C("Primal Vigor", "Enchantment", {"gen": 4, "G": 1}, priority=7.5,
      threat=7.5),
]

# ---------------------------------------------------------------------------
# Value creatures and recursion
# ---------------------------------------------------------------------------
VALUE = [
    C("Sun Titan", "Creature", {"gen": 4, "W": 2}, 6, 6, priority=7.5,
      threat=8.0),
    C("Karmic Guide", "Creature", {"gen": 3, "W": 2}, 2, 2, priority=6,
      threat=5.5),
    C("Eternal Witness", "Creature", {"gen": 1, "G": 2}, 2, 1, priority=6,
      threat=4.5),
    C("Timeless Witness", "Creature", {"gen": 2, "G": 2}, 2, 1,
      priority=5.5, threat=4.5),
    C("Archon of Valor's Reach", "Creature", {"gen": 4, "G": 1, "W": 1}, 5, 6,
      priority=6.5, threat=7.0),
    C("Angel of Sanctions", "Creature", {"gen": 3, "W": 2}, 3, 4,
      priority=5.5, threat=6.0),
    C("Acidic Slime", "Creature", {"gen": 3, "G": 2}, 2, 2, priority=3.5,
      threat=4.0),
    C("Selfless Spirit", "Creature", {"gen": 1, "W": 1}, 2, 1, priority=5,
      threat=4.5),
    C("Ulvenwald Hydra", "Creature", {"gen": 4, "G": 2}, 0, 0,
      priority=6, threat=6.5),
]

# ---------------------------------------------------------------------------
# Card advantage, life, and the payoff
# ---------------------------------------------------------------------------
ENGINES = [
    C("Mirari's Wake", "Enchantment", {"gen": 3, "G": 1, "W": 1},
      priority=9.5, threat=7.5),  # §0z110: priority 7.5 -> 9.5, adopted 2026-10-05
    C("Sylvan Library", "Enchantment", {"gen": 1, "G": 1}, priority=7,
      threat=5.5),
    C("Alhammarret's Archive", "Artifact", {"gen": 5}, priority=6.5,
      threat=6.5),
    C("Aetherflux Reservoir", "Artifact", {"gen": 4}, priority=6.5,
      threat=8.0),
    C("Greater Good", "Enchantment", {"gen": 2, "G": 2}, priority=5,
      threat=5.0),
    C("Defense of the Heart", "Enchantment", {"gen": 3, "G": 1},
      priority=5, threat=5.0),
    C("Lightning Greaves", "Artifact", {"gen": 2}, priority=6, threat=4.0),
    C("Aura Shards", "Enchantment", {"gen": 1, "G": 1, "W": 1},
      priority=4, threat=6.0),
]

# ---------------------------------------------------------------------------
# Tutors. Chord of Calling and Green Sun's Zenith are X spells: the cost here
# is the pips alone and the engine picks X from the target it can afford.
# ---------------------------------------------------------------------------
TUTORS = [
    C("Chord of Calling", "Instant", {"G": 3}, priority=6.5),
    C("Green Sun's Zenith", "Sorcery", {"G": 1}, priority=7),
    C("Worldly Tutor", "Instant", {"G": 1}, priority=6),
    C("Enlightened Tutor", "Instant", {"W": 1}, priority=6),
    C("Eladamri's Call", "Instant", {"G": 1, "W": 1}, priority=6),
    C("Congregation at Dawn", "Instant", {"G": 2, "W": 1}, priority=5.5),
]

# ---------------------------------------------------------------------------
# Ramp
# ---------------------------------------------------------------------------
RAMP = [
    C("Sol Ring", "Artifact", {"gen": 1}, priority=10, threat=4.0,
      mana=(2, "C")),
    C("Arcane Signet", "Artifact", {"gen": 2}, priority=9, mana=(1, "WG")),
    C("Talisman of Unity", "Artifact", {"gen": 2}, priority=8.5,
      mana=(1, "WGC")),
    C("Birds of Paradise", "Creature", {"G": 1}, 0, 1, priority=9,
      mana=(1, "WG")),
    C("Elvish Mystic", "Creature", {"G": 1}, 1, 1, priority=9,
      mana=(1, "G")),
    C("Avacyn's Pilgrim", "Creature", {"G": 1}, 1, 1, priority=9,
      mana=(1, "W")),
    C("Sylvan Caryatid", "Creature", {"gen": 1, "G": 1}, 0, 3,
      priority=8.5, mana=(1, "WG")),
    C("Sakura-Tribe Elder", "Creature", {"gen": 1, "G": 1}, 1, 1,
      priority=8),
    C("Wood Elves", "Creature", {"gen": 2, "G": 1}, 1, 1, priority=7.5),
    C("Farhaven Elf", "Creature", {"gen": 2, "G": 1}, 1, 1, priority=7.5),
    C("Solemn Simulacrum", "Artifact/Creature", {"gen": 4}, 2, 2,
      priority=7),
    C("Skyshroud Claim", "Sorcery", {"gen": 3, "G": 1}, priority=6.5),
]

# ---------------------------------------------------------------------------
# Interaction -- MODEL-BLIND against an abstract pod (§4), Wrath of God aside,
# which is a symmetric wipe and PARTLY by construction.
# ---------------------------------------------------------------------------
INTERACTION = [
    C("Swords to Plowshares", "Instant", {"W": 1}, priority=3),
    C("Path to Exile", "Instant", {"W": 1}, priority=3),
    C("Beast Within", "Instant", {"gen": 2, "G": 1}, priority=3),
    C("Wrath of God", "Sorcery", {"gen": 2, "W": 2}, priority=2,
      tags=("wipe",)),
]

# ---------------------------------------------------------------------------
# Lands -- 37
# ---------------------------------------------------------------------------
LANDS = (
    [L("Forest", "G")] * 7 + [L("Plains", "W")] * 9 +
    [
        L("Command Tower", "WG"),
        # "{T}: Add one mana of any color that a land an opponent controls
        # could produce." The pod's lands are not modelled (§4); a four-player
        # table nearly always offers both colours, so WG.
        L("Exotic Orchard", "WG"),
        # "...any type that a land you control could produce": with any other
        # land out, that is W or G in this list.
        L("Reflecting Pool", "WG"),
        # {1},{T}: Add {G}{W} -- a filter, modelled as a WG source. It
        # overstates the land only when it is your sole mana source.
        L("Sungrass Prairie", "WG"),
        L("Temple Garden", "WG", tags=("shock",)),
        L("Sunpetal Grove", "WG", tags=("check",)),
        L("Canopy Vista", "WG", tags=("battle",)),
        L("Fortified Village", "WG", tags=("reveal",)),
        L("Radiant Grove", "WG", tapped=True),
        L("Scattered Groves", "WG", tapped=True, tags=("cycling2",)),
        L("Blossoming Sands", "WG", tapped=True, tags=("gain1",)),
        L("Temple of Plenty", "WG", tapped=True, tags=("scry1",)),
        L("Selesnya Sanctuary", "WG", tapped=True, tags=("bounce",)),
        L("Mosswort Bridge", "G", tapped=True, tags=("hideaway4",)),
        # Cavern of Souls' coloured mode pays only for a creature spell of the
        # chosen type; modelled as {C} alone. A FLOOR on the land.
        L("Cavern of Souls", "C"),
        L("Yavimaya Hollow", "C"),
        L("Windswept Heath", "", tags=("fetch", "fetch_Forest",
                                       "fetch_Plains")),
        L("Verdant Catacombs", "", tags=("fetch", "fetch_Forest")),
        L("Misty Rainforest", "", tags=("fetch", "fetch_Forest")),
        L("Wooded Foothills", "", tags=("fetch", "fetch_Forest")),
        L("Flooded Strand", "", tags=("fetch", "fetch_Plains")),
        L("Marsh Flats", "", tags=("fetch", "fetch_Plains")),
    ]
)


def build():
    deck = (TOKENS + DOUBLERS + VALUE + ENGINES + TUTORS + RAMP
            + INTERACTION + LANDS)
    assert len(deck) == 99, f"deck is {len(deck)} cards, expected 99"
    return deck, COMMANDER
